export const PokemonDico: { [englishName: string]: string; } = {
	"Bulbasaur": "Bulbizarre",
	"Ivysaur": "Herbizarre",
	"Venusaur": "Florizarre",
	"Venusaur-Mega": "Florizarre-Méga",
	"Venusaur-Gmax": "Florizarre-Gmax",
	"Charmander": "Salamèche",
	"Charmeleon": "Reptincel",
	"Charizard": "Dracaufeu",
	"Charizard-Mega-X": "Dracaufeu-Méga-X",
	"Charizard-Mega-Y": "Dracaufeu-Méga-Y",
	"Charizard-Gmax": "Dracaufeu-Gmax",
	"Squirtle": "Carapuce",
	"Wartortle": "Carabaffe",
	"Blastoise": "Tortank",
	"Blastoise-Mega": "Tortank-Méga",
	"Caterpie": "Chenipan",
	"Metapod": "Chrysacier",
	"Butterfree": "Papilusion",
	"Butterfree-Gmax": "Papilusion-Gmax",
	"Weedle": "Aspicot",
	"Kakuna": "Coconfort",
	"Beedrill": "Dardargnan",
	"Beedrill-Mega": "Dardargnan-Méga",
	"Pidgey": "Roucool",
	"Pidgeotto": "Roucoups",
	"Pidgeot": "Roucarnage",
	"Pidgeot-Mega": "Roucarnage-Méga",
	"Rattata": "Rattata",
	"Rattata-Alola": "Rattata-Alola",
	"Raticate": "Rattatac",
	"Raticate-Alola": "Rattatac-Alola",
	"Raticate-Alola-Totem": "Rattatac-Alola-Dominant",
	"Spearow": "Piafabec",
	"Fearow": "Rapasdepic",
	"Ekans": "Abo",
	"Arbok": "Arbok",
	"Pikachu": "Pikachu",
	"Pikachu-Original": "Pikachu-Original",
	"Pikachu-Partner": "Pikachu-Partenaire",
	"Pikachu-Hoenn": "Pikachu-Hoenn",
	"Pikachu-Sinnoh": "Pikachu-Sinnoh",
	"Pikachu-Unova": "Pikachu-Unys",
	"Pikachu-Kalos": "Pikachu-Kalos",
	"Pikachu-Alola": "Pikachu-Alola",
	"Pikachu-World": "Pikachu-Monde",
	"Pikachu-Cosplay": "Pikachu-Cosplayeur",
	"Pikachu-Belle": "Pikachu-Lady",
	"Pikachu-Libre": "Pikachu-Catcheur",
	"Pikachu-PhD": "Pikachu-Docteur",
	"Pikachu-Pop-Star": "Pikachu-Star",
	"Pikachu-Rock-Star": "Pikachu-Rockeur",
	"Pikachu-Starter": "Pikachu-Starter",
	"Pikachu-Gmax": "Pikachu-Gmax",
	"Raichu": "Raichu",
	"Raichu-Alola": "Raichu-Alola",
	"Sandshrew": "Sabelette",
	"Sandshrew-Alola": "Sabelette-Alola",
	"Sandslash": "Sablaireau",
	"Sandslash-Alola": "Sablaireau-Alola",
	"Nidoran-F": "Nidoran-F",
	"Nidorina": "Nidorina",
	"Nidoqueen": "Nidoqueen",
	"Nidoran-M": "Nidoran-M",
	"Nidorino": "Nidorino",
	"Nidoking": "Nidoking",
	"Clefairy": "Mélofée",
	"Clefable": "Mélodelfe",
	"Vulpix": "Goupix",
	"Vulpix-Alola": "Goupix-Alola",
	"Ninetales": "Feunard",
	"Ninetales-Alola": "Feunard-Alola",
	"Jigglypuff": "Rondoudou",
	"Wigglytuff": "Grodoudou",
	"Zubat": "Nosferapti",
	"Golbat": "Nosferalto",
	"Oddish": "Mystherbe",
	"Gloom": "Ortide",
	"Vileplume": "Rafflesia",
	"Paras": "Paras",
	"Parasect": "Parasect",
	"Venonat": "Mimitoss",
	"Venomoth": "Aéromite",
	"Diglett": "Taupiqueur",
	"Diglett-Alola": "Taupiqueur-Alola",
	"Dugtrio": "Triopikeur",
	"Dugtrio-Alola": "Triopikeur-Alola",
	"Meowth": "Miaouss",
	"Meowth-Alola": "Miaouss-Alola",
	"Meowth-Galar": "Miaouss-Galar",
	"Meowth-Gmax": "Miaouss-Gmax",
	"Persian": "Persian",
	"Persian-Alola": "Persian-Alola",
	"Psyduck": "Psykokwak",
	"Golduck": "Akwakwak",
	"Mankey": "Férosinge",
	"Primeape": "Colossinge",
	"Growlithe": "Caninos",
	"Growlithe-Hisui": "Caninos-Hisui",
	"Arcanine": "Arcanin",
	"Arcanine-Hisui": "Arcanin-Hisui",
	"Poliwag": "Ptitard",
	"Poliwhirl": "Têtarte",
	"Poliwrath": "Tartard",
	"Abra": "Abra",
	"Kadabra": "Kadabra",
	"Alakazam": "Alakazam",
	"Alakazam-Mega": "Alakazam-Méga",
	"Machop": "Machoc",
	"Machoke": "Machopeur",
	"Machamp": "Mackogneur",
	"Machamp-Gmax": "Mackogneur-Gmax",
	"Bellsprout": "Chétiflor",
	"Weepinbell": "Boustiflor",
	"Victreebel": "Empiflor",
	"Tentacool": "Tentacool",
	"Tentacruel": "Tentacruel",
	"Geodude": "Racaillou",
	"Geodude-Alola": "Racaillou-Alola",
	"Graveler": "Gravalanch",
	"Graveler-Alola": "Gravalanch-Alola",
	"Golem": "Grolem",
	"Golem-Alola": "Grolem-Alola",
	"Ponyta": "Ponyta",
	"Ponyta-Galar": "Ponyta-Galar",
	"Rapidash": "Galopa",
	"Rapidash-Galar": "Galopa-Galar",
	"Slowpoke": "Ramoloss",
	"Slowpoke-Galar": "Ramoloss-Galar",
	"Slowbro": "Flagadoss",
	"Slowbro-Mega": "Flagadoss-Méga",
	"Slowbro-Galar": "Flagadoss-Galar",
	"Magnemite": "Magnéti",
	"Magneton": "Magnéton",
	"Farfetch’d": "Canarticho",
	"Farfetch’d-Galar": "Canarticho-Galar",
	"Doduo": "Doduo",
	"Dodrio": "Dodrio",
	"Seel": "Otaria",
	"Dewgong": "Lamantine",
	"Grimer": "Tadmorv",
	"Grimer-Alola": "Tadmorv-Alola",
	"Muk": "Grotadmorv",
	"Muk-Alola": "Grotadmorv-Alola",
	"Shellder": "Kokiyas",
	"Cloyster": "Crustabri",
	"Gastly": "Fantominus",
	"Haunter": "Spectrum",
	"Gengar": "Ectoplasma",
	"Gengar-Mega": "Ectoplasma-Méga",
	"Gengar-Gmax": "Ectoplasma-Gmax",
	"Onix": "Onix",
	"Drowzee": "Soporifik",
	"Hypno": "Hypnomade",
	"Krabby": "Krabby",
	"Kingler": "Krabboss",
	"Kingler-Gmax": "Krabboss-Gmax",
	"Voltorb": "Voltorbe",
	"Voltorb-Hisui": "Voltorbe-Hisui",
	"Electrode": "Électrode",
	"Electrode-Hisui": "Électrode-Hisui",
	"Exeggcute": "Noeunoeuf",
	"Exeggutor": "Noadkoko",
	"Exeggutor-Alola": "Noadkoko-Alola",
	"Cubone": "Osselait",
	"Marowak": "Ossatueur",
	"Marowak-Alola": "Ossatueur-Alola",
	"Marowak-Alola-Totem": "Ossatueur-Alola-Dominant",
	"Hitmonlee": "Kicklee",
	"Hitmonchan": "Tygnon",
	"Lickitung": "Excelangue",
	"Koffing": "Smogo",
	"Weezing": "Smogogo",
	"Weezing-Galar": "Smogogo-Galar",
	"Rhyhorn": "Rhinocorne",
	"Rhydon": "Rhinoféros",
	"Chansey": "Leveinard",
	"Tangela": "Saquedeneu",
	"Kangaskhan": "Kangourex",
	"Kangaskhan-Mega": "Kangourex-Méga",
	"Horsea": "Hypotrempe",
	"Seadra": "Hypocéan",
	"Goldeen": "Poissirène",
	"Seaking": "Poissoroy",
	"Staryu": "Stari",
	"Starmie": "Staross",
	"Mr. Mime": "M. Mime",
	"Mr. Mime-Galar": "M. Mime-Galar",
	"Scyther": "Insécateur",
	"Jynx": "Lippoutou",
	"Electabuzz": "Élektek",
	"Magmar": "Magmar",
	"Pinsir": "Scarabrute",
	"Pinsir-Mega": "Scarabrute-Méga",
	"Tauros": "Tauros",
	"Magikarp": "Magicarpe",
	"Gyarados": "Léviator",
	"Gyarados-Mega": "Léviator-Méga",
	"Lapras": "Lokhlass",
	"Lapras-Gmax": "Lokhlass-Gmax",
	"Ditto": "Métamorph",
	"Eevee": "Évoli",
	"Eevee-Starter": "Évoli-Starter",
	"Eevee-Gmax": "Évoli-Gmax",
	"Vaporeon": "Aquali",
	"Jolteon": "Voltali",
	"Flareon": "Pyroli",
	"Porygon": "Porygon",
	"Omanyte": "Amonita",
	"Omastar": "Amonistar",
	"Kabuto": "Kabuto",
	"Kabutops": "Kabutops",
	"Aerodactyl": "Ptéra",
	"Aerodactyl-Mega": "Ptéra-Méga",
	"Snorlax": "Ronflex",
	"Snorlax-Gmax": "Ronflex-Gmax",
	"Articuno": "Artikodin",
	"Articuno-Galar": "Artikodin-Galar",
	"Zapdos": "Électhor",
	"Zapdos-Galar": "Électhor-Galar",
	"Moltres": "Sulfura",
	"Moltres-Galar": "Sulfura-Galar",
	"Dratini": "Minidraco",
	"Dragonair": "Draco",
	"Dragonite": "Dracolosse",
	"Mewtwo": "Mewtwo",
	"Mewtwo-Mega-X": "Mewtwo-Méga-X",
	"Mewtwo-Mega-Y": "Mewtwo-Méga-Y",
	"Mew": "Mew",
	"Chikorita": "Germignon",
	"Bayleef": "Macronium",
	"Meganium": "Méganium",
	"Cyndaquil": "Héricendre",
	"Quilava": "Feurisson",
	"Typhlosion": "Typhlosion",
	"Typhlosion-Hisui": "Typhlosion-Hisui",
	"Totodile": "Kaiminus",
	"Croconaw": "Crocrodil",
	"Feraligatr": "Aligatueur",
	"Sentret": "Fouinette",
	"Furret": "Fouinar",
	"Hoothoot": "Hoothoot",
	"Noctowl": "Noarfang",
	"Ledyba": "Coxy",
	"Ledian": "Coxyclaque",
	"Spinarak": "Mimigal",
	"Ariados": "Migalos",
	"Crobat": "Nostenfer",
	"Chinchou": "Loupio",
	"Lanturn": "Lanturn",
	"Pichu": "Pichu",
	"Pichu-Spiky-eared": "Pichu-Troizépi",
	"Cleffa": "Mélo",
	"Igglybuff": "Toudoudou",
	"Togepi": "Togepi",
	"Togetic": "Togetic",
	"Natu": "Natu",
	"Xatu": "Xatu",
	"Mareep": "Wattouat",
	"Flaaffy": "Lainergie",
	"Ampharos": "Pharamp",
	"Ampharos-Mega": "Pharamp-Méga",
	"Bellossom": "Joliflor",
	"Marill": "Marill",
	"Azumarill": "Azumarill",
	"Sudowoodo": "Simularbre",
	"Politoed": "Tarpaud",
	"Hoppip": "Granivol",
	"Skiploom": "Floravol",
	"Jumpluff": "Cotovol",
	"Aipom": "Capumain",
	"Sunkern": "Tournegrin",
	"Sunflora": "Héliatronc",
	"Yanma": "Yanma",
	"Wooper": "Axoloto",
	"Quagsire": "Maraiste",
	"Espeon": "Mentali",
	"Umbreon": "Noctali",
	"Murkrow": "Cornèbre",
	"Slowking": "Roigada",
	"Slowking-Galar": "Roigada-Galar",
	"Misdreavus": "Feuforêve",
	"Unown": "Zarbi",
	"Unown-B": "Zarbi-B",
	"Unown-C": "Zarbi-C",
	"Unown-D": "Zarbi-D",
	"Unown-E": "Zarbi-E",
	"Unown-F": "Zarbi-F",
	"Unown-G": "Zarbi-G",
	"Unown-H": "Zarbi-H",
	"Unown-I": "Zarbi-I",
	"Unown-J": "Zarbi-J",
	"Unown-K": "Zarbi-K",
	"Unown-L": "Zarbi-L",
	"Unown-M": "Zarbi-M",
	"Unown-N": "Zarbi-N",
	"Unown-O": "Zarbi-O",
	"Unown-P": "Zarbi-P",
	"Unown-Q": "Zarbi-Q",
	"Unown-R": "Zarbi-R",
	"Unown-S": "Zarbi-S",
	"Unown-T": "Zarbi-T",
	"Unown-U": "Zarbi-U",
	"Unown-V": "Zarbi-V",
	"Unown-W": "Zarbi-W",
	"Unown-X": "Zarbi-X",
	"Unown-Y": "Zarbi-Y",
	"Unown-Z": "Zarbi-Z",
	"Unown-Exclamation": "Zarbi-Exclamation",
	"Unown-Question": "Zarbi-Question",
	"Wobbuffet": "Qulbutoké",
	"Girafarig": "Girafarig",
	"Pineco": "Pomdepik",
	"Forretress": "Foretress",
	"Dunsparce": "Insolourdo",
	"Gligar": "Scorplane",
	"Steelix": "Steelix",
	"Steelix-Mega": "Steelix-Méga",
	"Snubbull": "Snubbull",
	"Granbull": "Granbull",
	"Qwilfish": "Qwilfish",
	"Qwilfish-Hisui": "Qwilfish-Hisui",
	"Scizor": "Cizayox",
	"Scizor-Mega": "Cizayox-Méga",
	"Shuckle": "Caratroc",
	"Heracross": "Scarhino",
	"Heracross-Mega": "Scarhino-Méga",
	"Sneasel": "Farfuret",
	"Sneasel-Hisui": "Farfuret-Hisui",
	"Teddiursa": "Teddiursa",
	"Ursaring": "Ursaring",
	"Slugma": "Limagma",
	"Magcargo": "Volcaropod",
	"Swinub": "Marcacrin",
	"Piloswine": "Cochignon",
	"Corsola": "Corayon",
	"Corsola-Galar": "Corayon-Galar",
	"Remoraid": "Rémoraid",
	"Octillery": "Octillery",
	"Delibird": "Cadoizo",
	"Mantine": "Démanta",
	"Skarmory": "Airmure",
	"Houndour": "Malosse",
	"Houndoom": "Démolosse",
	"Houndoom-Mega": "Démolosse-Méga",
	"Kingdra": "Hyporoi",
	"Phanpy": "Phanpy",
	"Donphan": "Donphan",
	"Porygon2": "Porygon2",
	"Stantler": "Cerfrousse",
	"Smeargle": "Queulorior",
	"Tyrogue": "Debugant",
	"Hitmontop": "Kapoera",
	"Smoochum": "Lippouti",
	"Elekid": "Élekid",
	"Magby": "Magby",
	"Miltank": "Écrémeuh",
	"Blissey": "Leuphorie",
	"Raikou": "Raikou",
	"Entei": "Entei",
	"Suicune": "Suicune",
	"Larvitar": "Embrylex",
	"Pupitar": "Ymphect",
	"Tyranitar": "Tyranocif",
	"Tyranitar-Mega": "Tyranocif-Méga",
	"Lugia": "Lugia",
	"Ho-Oh": "Ho-Oh",
	"Celebi": "Celebi",
	"Treecko": "Arcko",
	"Grovyle": "Massko",
	"Sceptile": "Jungko",
	"Sceptile-Mega": "Jungko-Méga",
	"Torchic": "Poussifeu",
	"Combusken": "Galifeu",
	"Blaziken": "Braségali",
	"Blaziken-Mega": "Braségali-Méga",
	"Mudkip": "Gobou",
	"Marshtomp": "Flobio",
	"Swampert": "Laggron",
	"Swampert-Mega": "Laggron-Méga",
	"Poochyena": "Medhyèna",
	"Mightyena": "Grahyèna",
	"Zigzagoon": "Zigzaton",
	"Zigzagoon-Galar": "Zigzaton-Galar",
	"Linoone": "Linéon",
	"Linoone-Galar": "Linéon-Galar",
	"Wurmple": "Chenipotte",
	"Silcoon": "Armulys",
	"Beautifly": "Charmillon",
	"Cascoon": "Blindalys",
	"Dustox": "Papinox",
	"Lotad": "Nénupiot",
	"Lombre": "Lombre",
	"Ludicolo": "Ludicolo",
	"Seedot": "Grainipiot",
	"Nuzleaf": "Pifeuil",
	"Shiftry": "Tengalice",
	"Taillow": "Nirondelle",
	"Swellow": "Hélédelle",
	"Wingull": "Goélise",
	"Pelipper": "Bekipan",
	"Ralts": "Tarsal",
	"Kirlia": "Kirlia",
	"Gardevoir": "Gardevoir",
	"Gardevoir-Mega": "Gardevoir-Méga",
	"Surskit": "Arakdo",
	"Masquerain": "Maskadra",
	"Shroomish": "Balignon",
	"Breloom": "Chapignon",
	"Slakoth": "Parecool",
	"Vigoroth": "Vigoroth",
	"Slaking": "Monaflèmit",
	"Nincada": "Ningale",
	"Ninjask": "Ninjask",
	"Shedinja": "Munja",
	"Whismur": "Chuchmur",
	"Loudred": "Ramboum",
	"Exploud": "Brouhabam",
	"Makuhita": "Makuhita",
	"Hariyama": "Hariyama",
	"Azurill": "Azurill",
	"Nosepass": "Tarinor",
	"Skitty": "Skitty",
	"Delcatty": "Delcatty",
	"Sableye": "Ténéfix",
	"Sableye-Mega": "Ténéfix-Méga",
	"Mawile": "Mysdibule",
	"Mawile-Mega": "Mysdibule-Méga",
	"Aron": "Galekid",
	"Lairon": "Galegon",
	"Aggron": "Galeking",
	"Aggron-Mega": "Galeking-Méga",
	"Meditite": "Méditikka",
	"Medicham": "Charmina",
	"Medicham-Mega": "Charmina-Méga",
	"Electrike": "Dynavolt",
	"Manectric": "Élecsprint",
	"Manectric-Mega": "Élecsprint-Méga",
	"Plusle": "Posipi",
	"Minun": "Négapi",
	"Volbeat": "Muciole",
	"Illumise": "Lumivole",
	"Roselia": "Rosélia",
	"Gulpin": "Gloupti",
	"Swalot": "Avaltout",
	"Carvanha": "Carvanha",
	"Sharpedo": "Sharpedo",
	"Sharpedo-Mega": "Sharpedo-Méga",
	"Wailmer": "Wailmer",
	"Wailord": "Wailord",
	"Numel": "Chamallot",
	"Camerupt": "Camérupt",
	"Camerupt-Mega": "Camérupt-Méga",
	"Torkoal": "Chartor",
	"Spoink": "Spoink",
	"Grumpig": "Groret",
	"Spinda": "Spinda",
	"Trapinch": "Kraknoix",
	"Vibrava": "Vibraninf",
	"Flygon": "Libégon",
	"Cacnea": "Cacnea",
	"Cacturne": "Cacturne",
	"Swablu": "Tylton",
	"Altaria": "Altaria",
	"Altaria-Mega": "Altaria-Méga",
	"Zangoose": "Mangriff",
	"Seviper": "Séviper",
	"Lunatone": "Séléroc",
	"Solrock": "Solaroc",
	"Barboach": "Barloche",
	"Whiscash": "Barbicha",
	"Corphish": "Écrapince",
	"Crawdaunt": "Colhomard",
	"Baltoy": "Balbuto",
	"Claydol": "Kaorine",
	"Lileep": "Lilia",
	"Cradily": "Vacilys",
	"Anorith": "Anorith",
	"Armaldo": "Armaldo",
	"Feebas": "Barpau",
	"Milotic": "Milobellus",
	"Castform": "Morphéo",
	"Castform-Rainy": "Morphéo-Eau de Pluie",
	"Castform-Snowy": "Morphéo-Blizzard",
	"Castform-Sunny": "Morphéo-Solaire",
	"Kecleon": "Kecleon",
	"Shuppet": "Polichombr",
	"Banette": "Branette",
	"Banette-Mega": "Branette-Méga",
	"Duskull": "Skelénox",
	"Dusclops": "Téraclope",
	"Tropius": "Tropius",
	"Chimecho": "Éoko",
	"Absol": "Absol",
	"Absol-Mega": "Absol-Méga",
	"Wynaut": "Okéoké",
	"Snorunt": "Stalgamin",
	"Glalie": "Oniglali",
	"Glalie-Mega": "Oniglali-Méga",
	"Spheal": "Obalie",
	"Sealeo": "Phogleur",
	"Walrein": "Kaimorse",
	"Clamperl": "Coquiperl",
	"Huntail": "Serpang",
	"Gorebyss": "Rosabyss",
	"Relicanth": "Relicanth",
	"Luvdisc": "Lovdisc",
	"Bagon": "Draby",
	"Shelgon": "Drackhaus",
	"Salamence": "Drattak",
	"Salamence-Mega": "Drattak-Méga",
	"Beldum": "Terhal",
	"Metang": "Métang",
	"Metagross": "Métalosse",
	"Metagross-Mega": "Métalosse-Méga",
	"Regirock": "Regirock",
	"Regice": "Regice",
	"Registeel": "Registeel",
	"Latias": "Latias",
	"Latias-Mega": "Latias-Méga",
	"Latios": "Latios",
	"Latios-Mega": "Latios-Méga",
	"Kyogre": "Kyogre",
	"Kyogre-Primal": "Kyogre-Primo",
	"Groudon": "Groudon",
	"Groudon-Primal": "Groudon-Primo",
	"Rayquaza": "Rayquaza",
	"Rayquaza-Mega": "Rayquaza-Méga",
	"Jirachi": "Jirachi",
	"Deoxys": "Deoxys",
	"Deoxys-Attack": "Deoxys-Attaque",
	"Deoxys-Defense": "Deoxys-Défense",
	"Deoxys-Speed": "Deoxys-Vitesse",
	"Turtwig": "Tortipouss",
	"Grotle": "Boskara",
	"Torterra": "Torterra",
	"Chimchar": "Ouisticram",
	"Monferno": "Chimpenfeu",
	"Infernape": "Simiabraz",
	"Piplup": "Tiplouf",
	"Prinplup": "Prinplouf",
	"Empoleon": "Pingoléon",
	"Starly": "Étourmi",
	"Staravia": "Étourvol",
	"Staraptor": "Étouraptor",
	"Bidoof": "Keunotor",
	"Bibarel": "Castorno",
	"Kricketot": "Crikzik",
	"Kricketune": "Mélokrik",
	"Shinx": "Lixy",
	"Luxio": "Luxio",
	"Luxray": "Luxray",
	"Budew": "Rozbouton",
	"Roserade": "Roserade",
	"Cranidos": "Kranidos",
	"Rampardos": "Charkos",
	"Shieldon": "Dinoclier",
	"Bastiodon": "Bastiodon",
	"Burmy": "Cheniti",
	"Burmy-Sandy": "Cheniti-Sable",
	"Burmy-Trash": "Cheniti-Déchet",
	"Wormadam": "Cheniselle",
	"Wormadam-Sandy": "Cheniselle-Sable",
	"Wormadam-Trash": "Cheniselle-Déchet",
	"Mothim": "Papilord",
	"Combee": "Apitrini",
	"Vespiquen": "Apireine",
	"Pachirisu": "Pachirisu",
	"Buizel": "Mustébouée",
	"Floatzel": "Mustéflott",
	"Cherubi": "Ceribou",
	"Cherrim": "Ceriflor",
	"Cherrim-Sunshine": "Ceriflor-Ensoleillé",
	"Shellos": "Sancoki",
	"Shellos-East": "Sancoki-Orient",
	"Gastrodon": "Tritosor",
	"Gastrodon-East": "Tritosor-Orient",
	"Ambipom": "Capidextre",
	"Drifloon": "Baudrive",
	"Drifblim": "Grodrive",
	"Buneary": "Laporeille",
	"Lopunny": "Lockpin",
	"Lopunny-Mega": "Lockpin-Méga",
	"Mismagius": "Magirêve",
	"Honchkrow": "Corboss",
	"Glameow": "Chaglam",
	"Purugly": "Chaffreux",
	"Chingling": "Korillon",
	"Stunky": "Moufouette",
	"Skuntank": "Moufflair",
	"Bronzor": "Archéomire",
	"Bronzong": "Archéodong",
	"Bonsly": "Manzaï",
	"Mime Jr.": "Mime Jr.",
	"Happiny": "Ptiravi",
	"Chatot": "Pijako",
	"Spiritomb": "Spiritomb",
	"Gible": "Griknot",
	"Gabite": "Carmache",
	"Garchomp": "Carchacrok",
	"Garchomp-Mega": "Carchacrok-Méga",
	"Munchlax": "Goinfrex",
	"Riolu": "Riolu",
	"Lucario": "Lucario",
	"Lucario-Mega": "Lucario-Méga",
	"Hippopotas": "Hippopotas",
	"Hippowdon": "Hippodocus",
	"Skorupi": "Rapion",
	"Drapion": "Drascore",
	"Croagunk": "Cradopaud",
	"Toxicroak": "Coatox",
	"Carnivine": "Vortente",
	"Finneon": "Écayon",
	"Lumineon": "Luminéon",
	"Mantyke": "Babimanta",
	"Snover": "Blizzi",
	"Abomasnow": "Blizzaroi",
	"Abomasnow-Mega": "Blizzaroi-Méga",
	"Weavile": "Dimoret",
	"Magnezone": "Magnézone",
	"Lickilicky": "Coudlangue",
	"Rhyperior": "Rhinastoc",
	"Tangrowth": "Bouldeneu",
	"Electivire": "Élekable",
	"Magmortar": "Maganon",
	"Togekiss": "Togekiss",
	"Yanmega": "Yanméga",
	"Leafeon": "Phyllali",
	"Glaceon": "Givrali",
	"Gliscor": "Scorvol",
	"Mamoswine": "Mammochon",
	"Porygon-Z": "Porygon-Z",
	"Gallade": "Gallame",
	"Gallade-Mega": "Gallame-Méga",
	"Probopass": "Tarinorme",
	"Dusknoir": "Noctunoir",
	"Froslass": "Momartik",
	"Rotom": "Motisma",
	"Rotom-Fan": "Motisma-Hélice",
	"Rotom-Frost": "Motisma-Froid",
	"Rotom-Heat": "Motisma-Chaleur",
	"Rotom-Mow": "Motisma-Tonte",
	"Rotom-Wash": "Motisma-Lavage",
	"Uxie": "Créhelf",
	"Mesprit": "Créfollet",
	"Azelf": "Créfadet",
	"Dialga": "Dialga",
	"Dialga-Origin": "Dialga-Origine",
	"Palkia": "Palkia",
	"Palkia-Origin": "Palkia-Origine",
	"Heatran": "Heatran",
	"Regigigas": "Regigigas",
	"Giratina": "Giratina",
	"Giratina-Origin": "Giratina-Origine",
	"Cresselia": "Cresselia",
	"Phione": "Phione",
	"Manaphy": "Manaphy",
	"Darkrai": "Darkrai",
	"Shaymin": "Shaymin",
	"Shaymin-Sky": "Shaymin-Céleste",
	"Arceus": "Arceus",
	"Arceus-Bug": "Arceus-Insecte",
	"Arceus-Dark": "Arceus-Ténèbres",
	"Arceus-Dragon": "Arceus-Dragon",
	"Arceus-Electric": "Arceus-Électrik",
	"Arceus-Fairy": "Arceus-Fée",
	"Arceus-Fighting": "Arceus-Combat",
	"Arceus-Fire": "Arceus-Feu",
	"Arceus-Flying": "Arceus-Vol",
	"Arceus-Ghost": "Arceus-Spectre",
	"Arceus-Grass": "Arceus-Plante",
	"Arceus-Ground": "Arceus-Sol",
	"Arceus-Ice": "Arceus-Glace",
	"Arceus-Poison": "Arceus-Poison",
	"Arceus-Psychic": "Arceus-Psy",
	"Arceus-Rock": "Arceus-Roche",
	"Arceus-Steel": "Arceus-Acier",
	"Arceus-Water": "Arceus-Eau",
	"Victini": "Victini",
	"Snivy": "Vipélierre",
	"Servine": "Lianaja",
	"Serperior": "Majaspic",
	"Tepig": "Gruikui",
	"Pignite": "Grotichon",
	"Emboar": "Roitiflam",
	"Oshawott": "Moustillon",
	"Dewott": "Mateloutre",
	"Samurott": "Clamiral",
	"Samurott-Hisui": "Clamiral-Hisui",
	"Patrat": "Ratentif",
	"Watchog": "Miradar",
	"Lillipup": "Ponchiot",
	"Herdier": "Ponchien",
	"Stoutland": "Mastouffe",
	"Purrloin": "Chacripan",
	"Liepard": "Léopardus",
	"Pansage": "Feuillajou",
	"Simisage": "Feuiloutan",
	"Pansear": "Flamajou",
	"Simisear": "Flamoutan",
	"Panpour": "Flotajou",
	"Simipour": "Flotoutan",
	"Munna": "Munna",
	"Musharna": "Mushana",
	"Pidove": "Poichigeon",
	"Tranquill": "Colombeau",
	"Unfezant": "Déflaisan",
	"Blitzle": "Zébribon",
	"Zebstrika": "Zéblitz",
	"Roggenrola": "Nodulithe",
	"Boldore": "Géolithe",
	"Gigalith": "Gigalithe",
	"Woobat": "Chovsourir",
	"Swoobat": "Rhinolove",
	"Drilbur": "Rototaupe",
	"Excadrill": "Minotaupe",
	"Audino": "Nanméouïe",
	"Audino-Mega": "Nanméouïe-Méga",
	"Timburr": "Charpenti",
	"Gurdurr": "Ouvrifier",
	"Conkeldurr": "Bétochef",
	"Tympole": "Tritonde",
	"Palpitoad": "Batracné",
	"Seismitoad": "Crapustule",
	"Throh": "Judokrak",
	"Sawk": "Karaclée",
	"Sewaddle": "Larveyette",
	"Swadloon": "Couverdure",
	"Leavanny": "Manternel",
	"Venipede": "Venipatte",
	"Whirlipede": "Scobolide",
	"Scolipede": "Brutapode",
	"Cottonee": "Doudouvet",
	"Whimsicott": "Farfaduvet",
	"Petilil": "Chlorobule",
	"Lilligant": "Fragilady",
	"Lilligant-Hisui": "Fragilady-Hisui",
	"Basculin": "Bargantua",
	"Basculin-Blue-Striped": "Bargantua-Bleu",
	"Basculin-White-Striped": "Bargantua-Blanc",
	"Sandile": "Mascaïman",
	"Krokorok": "Escroco",
	"Krookodile": "Crocorible",
	"Darumaka": "Darumarond",
	"Darumaka-Galar": "Darumarond-Galar",
	"Darmanitan": "Darumacho",
	"Darmanitan-Zen": "Darumacho-Transe",
	"Darmanitan-Galar": "Darumacho-Galar",
	"Darmanitan-Galar-Zen": "Darumacho-Galar-Transe",
	"Maractus": "Maracachi",
	"Dwebble": "Crabicoque",
	"Crustle": "Crabaraque",
	"Scraggy": "Baggiguane",
	"Scrafty": "Baggaïd",
	"Sigilyph": "Cryptéro",
	"Yamask": "Tutafeh",
	"Yamask-Galar": "Tutafeh-Galar",
	"Cofagrigus": "Tutankafer",
	"Tirtouga": "Carapagos",
	"Carracosta": "Mégapagos",
	"Archen": "Arkéapti",
	"Archeops": "Aéroptéryx",
	"Trubbish": "Miamiasme",
	"Garbodor-Gmax": "Miasmax-Gmax",
	"Garbodor": "Miasmax",
	"Zorua": "Zorua",
	"Zorua-Hisui": "Zorua-Hisui",
	"Zoroark": "Zoroark",
	"Zoroark-Hisui": "Zoroark-Hisui",
	"Minccino": "Chinchidou",
	"Cinccino": "Pashmilla",
	"Gothita": "Scrutella",
	"Gothorita": "Mesmérella",
	"Gothitelle": "Sidérella",
	"Solosis": "Nucléos",
	"Duosion": "Méios",
	"Reuniclus": "Symbios",
	"Ducklett": "Couaneton",
	"Swanna": "Lakmécygne",
	"Vanillite": "Sorbébé",
	"Vanillish": "Sorboul",
	"Vanilluxe": "Sorbouboul",
	"Deerling": "Vivaldaim",
	"Deerling-Autumn": "Vivaldaim-Automne",
	"Deerling-Summer": "Vivaldaim-Été",
	"Deerling-Winter": "Vivaldaim-Hiver",
	"Sawsbuck": "Haydaim",
	"Sawsbuck-Autumn": "Haydaim-Automne",
	"Sawsbuck-Summer": "Haydaim-Été",
	"Sawsbuck-Winter": "Haydaim-Hiver",
	"Emolga": "Emolga",
	"Karrablast": "Carabing",
	"Escavalier": "Lançargot",
	"Foongus": "Trompignon",
	"Amoonguss": "Gaulet",
	"Frillish": "Viskuse",
	"Jellicent": "Moyade",
	"Alomomola": "Mamanbo",
	"Joltik": "Statitik",
	"Galvantula": "Mygavolt",
	"Ferroseed": "Grindur",
	"Ferrothorn": "Noacier",
	"Klink": "Tic",
	"Klang": "Clic",
	"Klinklang": "Cliticlic",
	"Tynamo": "Anchwatt",
	"Eelektrik": "Lampéroie",
	"Eelektross": "Ohmassacre",
	"Elgyem": "Lewsor",
	"Beheeyem": "Neitram",
	"Litwick": "Funécire",
	"Lampent": "Mélancolux",
	"Chandelure": "Lugulabre",
	"Axew": "Coupenotte",
	"Fraxure": "Incisache",
	"Haxorus": "Tranchodon",
	"Cubchoo": "Polarhume",
	"Beartic": "Polagriffe",
	"Cryogonal": "Hexagel",
	"Shelmet": "Escargaume",
	"Accelgor": "Limaspeed",
	"Stunfisk": "Limonde",
	"Stunfisk-Galar": "Limonde-Galar",
	"Mienfoo": "Kungfouine",
	"Mienshao": "Shaofouine",
	"Druddigon": "Drakkarmin",
	"Golett": "Gringolem",
	"Golurk": "Golemastoc",
	"Pawniard": "Scalpion",
	"Bisharp": "Scalproie",
	"Bouffalant": "Frison",
	"Rufflet": "Furaiglon",
	"Braviary": "Gueriaigle",
	"Braviary-Hisui": "Gueriaigle-Hisui",
	"Vullaby": "Vostourno",
	"Mandibuzz": "Vaututrice",
	"Heatmor": "Aflamanoir",
	"Durant": "Fermite",
	"Deino": "Solochi",
	"Zweilous": "Diamat",
	"Hydreigon": "Trioxhydre",
	"Larvesta": "Pyronille",
	"Volcarona": "Pyrax",
	"Cobalion": "Cobaltium",
	"Terrakion": "Terrakium",
	"Virizion": "Viridium",
	"Tornadus": "Boréas",
	"Tornadus-Therian": "Boréas-Totem",
	"Thundurus": "Fulguris",
	"Thundurus-Therian": "Fulguris-Totem",
	"Reshiram": "Reshiram",
	"Zekrom": "Zekrom",
	"Landorus": "Démétéros",
	"Landorus-Therian": "Démétéros-Totem",
	"Kyurem": "Kyurem",
	"Kyurem-Black": "Kyurem-Noir",
	"Kyurem-White": "Kyurem-Blanc",
	"Keldeo": "Keldeo",
	"Keldeo-Resolute": "Keldeo-Décidé",
	"Meloetta": "Meloetta",
	"Meloetta-Pirouette": "Meloetta-Danse",
	"Genesect": "Genesect",
	"Genesect-Burn": "Genesect-Pyro",
	"Genesect-Chill": "Genesect-Cryo",
	"Genesect-Douse": "Genesect-Aqua",
	"Genesect-Shock": "Genesect-Choc",
	"Chespin": "Marisson",
	"Quilladin": "Boguérisse",
	"Chesnaught": "Blindépique",
	"Fennekin": "Feunnec",
	"Braixen": "Roussil",
	"Delphox": "Goupelin",
	"Froakie": "Grenousse",
	"Frogadier": "Croâporal",
	"Greninja": "Amphinobi",
	"Greninja-Ash": "Amphinobi-Sacha",
	"Bunnelby": "Sapereau",
	"Diggersby": "Excavarenne",
	"Fletchling": "Passerouge",
	"Fletchinder": "Braisillon",
	"Talonflame": "Flambusard",
	"Scatterbug": "Lépidonille",
	"Spewpa": "Pérégrain",
	"Vivillon": "Prismillon",
	"Vivillon-Archipelago": "Prismillon-Archipel",
	"Vivillon-Continental": "Prismillon-Continent",
	"Vivillon-Elegant": "Prismillon-Monarchie",
	"Vivillon-Garden": "Prismillon-Verdure",
	"Vivillon-High Plains": "Prismillon-Sécheresse",
	"Vivillon-Icy Snow": "Prismillon-Blizzard",
	"Vivillon-Jungle": "Prismillon-Jungle",
	"Vivillon-Marine": "Prismillon-Rivage",
	"Vivillon-Modern": "Prismillon-Métropole",
	"Vivillon-Monsoon": "Prismillon-Cyclone",
	"Vivillon-Ocean": "Prismillon-Soleil Levant",
	"Vivillon-Polar": "Prismillon-Banquise",
	"Vivillon-River": "Prismillon-Delta",
	"Vivillon-Sandstorm": "Prismillon-Sable",
	"Vivillon-Savanna": "Prismillon-Mangrove",
	"Vivillon-Sun": "Prismillon-Zénith",
	"Vivillon-Tundra": "Prismillon-Glace",
	"Vivillon-Fancy": "Prismillon-Fantaisie",
	"Vivillon-Pokeball": "Prismillon-Pokéball",
	"Litleo": "Hélionceau",
	"Pyroar": "Némélios",
	"Flabe\u0301be\u0301": "Flabébé",
	"Flabe\u0301be\u0301-Blue": "Flabébé-Bleu",
	"Flabe\u0301be\u0301-Orange": "Flabébé-Orange",
	"Flabe\u0301be\u0301-White": "Flabébé-Blanc",
	"Flabe\u0301be\u0301-Yellow": "Flabébé-Jaune",
	"Floette": "Floette",
	"Floette-Blue": "Floette-Bleu",
	"Floette-Orange": "Floette-Orange",
	"Floette-White": "Floette-Blanc",
	"Floette-Yellow": "Floette-Jaune",
	"Floette-Eternal": "Floette-Éternelle",
	"Florges": "Florges",
	"Florges-Blue": "Florges-Bleu",
	"Florges-Orange": "Florges-Orange",
	"Florges-White": "Florges-Blanc",
	"Florges-Yellow": "Florges-Jaune",
	"Skiddo": "Cabriolaine",
	"Gogoat": "Chevroum",
	"Pancham": "Pandespiègle",
	"Pangoro": "Pandarbare",
	"Furfrou": "Couafarel",
	"Furfrou-Dandy": "Couafarel-Monsieur",
	"Furfrou-Debutante": "Couafarel-Demoiselle",
	"Furfrou-Heart": "Couafarel-Cœur",
	"Furfrou-Diamond": "Couafarel-Diamant",
	"Furfrou-Kabuki": "Couafarel-Kabuki",
	"Furfrou-La Reine": "Couafarel-Reine",
	"Furfrou-Matron": "Couafarel-Madame",
	"Furfrou-Pharaoh": "Couafarel-Pharaon",
	"Furfrou-Star": "Couafarel-Étoile",
	"Espurr": "Psystigri",
	"Meowstic": "Mistigrix",
	"Meowstic-F": "Mistigrix-F",
	"Honedge": "Monorpale",
	"Doublade": "Dimoclès",
	"Aegislash": "Exagide",
	"Aegislash-Blade": "Exagide-Épée",
	"Spritzee": "Fluvetin",
	"Aromatisse": "Cocotine",
	"Swirlix": "Sucroquin",
	"Slurpuff": "Cupcanaille",
	"Inkay": "Sepiatop",
	"Malamar": "Sepiatroce",
	"Binacle": "Opermine",
	"Barbaracle": "Golgopathe",
	"Skrelp": "Venalgue",
	"Dragalge": "Kravarech",
	"Clauncher": "Flingouste",
	"Clawitzer": "Gamblast",
	"Helioptile": "Galvaran",
	"Heliolisk": "Iguolta",
	"Tyrunt": "Ptyranidur",
	"Tyrantrum": "Rexillius",
	"Amaura": "Amagara",
	"Aurorus": "Dragmara",
	"Sylveon": "Nymphali",
	"Hawlucha": "Brutalibré",
	"Dedenne": "Dedenne",
	"Carbink": "Strassie",
	"Goomy": "Mucuscule",
	"Sliggoo": "Colimucus",
	"Sliggoo-Hisui": "Colimucus-Hisui",
	"Goodra": "Muplodocus",
	"Goodra-Hisui": "Muplodocus-Hisui",
	"Klefki": "Trousselin",
	"Phantump": "Brocélôme",
	"Trevenant": "Desséliande",
	"Pumpkaboo": "Pitrouille",
	"Pumpkaboo-Large": "Pitrouille-Maxi",
	"Pumpkaboo-Small": "Pitrouille-Mini",
	"Pumpkaboo-Super": "Pitrouille-Ultra",
	"Gourgeist": "Banshitrouye",
	"Gourgeist-Large": "Banshitrouye-Maxi",
	"Gourgeist-Small": "Banshitrouye-Mini",
	"Gourgeist-Super": "Banshitrouye-Ultra",
	"Bergmite": "Grelaçon",
	"Avalugg": "Séracrawl",
	"Avalugg-Hisui": "Séracrawl-Hisui",
	"Noibat": "Sonistrelle",
	"Noivern": "Bruyverne",
	"Xerneas": "Xerneas",
	"Xerneas-Neutral": "Xerneas-Paisible",
	"Yveltal": "Yveltal",
	"Zygarde": "Zygarde",
	"Zygarde-10%": "Zygarde-10%",
	"Zygarde-Complete": "Zygarde-Parfait",
	"Diancie": "Diancie",
	"Diancie-Mega": "Diancie-Méga",
	"Hoopa": "Hoopa",
	"Hoopa-Unbound": "Hoopa-Déchaîné",
	"Volcanion": "Volcanion",
	"Rowlet": "Brindibou",
	"Dartrix": "Efflèche",
	"Decidueye": "Archéduc",
	"Decidueye-Hisui": "Archéduc-Hisui",
	"Litten": "Flamiaou",
	"Torracat": "Matoufeu",
	"Incineroar": "Félinferno",
	"Popplio": "Otaquin",
	"Brionne": "Otarlette",
	"Primarina": "Oratoria",
	"Pikipek": "Picassaut",
	"Trumbeak": "Piclairon",
	"Toucannon": "Bazoucan",
	"Yungoos": "Manglouton",
	"Gumshoos": "Argouste",
	"Gumshoos-Totem": "Argouste-Dominant",
	"Grubbin": "Larvibule",
	"Charjabug": "Chrysapile",
	"Vikavolt": "Lucanon",
	"Vikavolt-Totem": "Lucanon-Dominant",
	"Crabrawler": "Crabagarre",
	"Crabominable": "Crabominable",
	"Oricorio": "Plumeline",
	"Oricorio-Pa'u": "Plumeline-Hula",
	"Oricorio-Pom-Pom": "Plumeline-Pom-Pom",
	"Oricorio-Sensu": "Plumeline-Buyō",
	"Cutiefly": "Bombydou",
	"Ribombee": "Rubombelle",
	"Ribombee-Totem": "Rubombelle-Dominant",
	"Rockruff": "Rocabot",
	"Lycanroc": "Lougaroc",
	"Lycanroc-Dusk": "Lougaroc-Crépuscule",
	"Lycanroc-Midnight": "Lougaroc-Nocturne",
	"Wishiwashi": "Froussardine",
	"Wishiwashi-School": "Froussardine-Banc",
	"Mareanie": "Vorastérie",
	"Toxapex": "Prédastérie",
	"Mudbray": "Tiboudet",
	"Mudsdale": "Bourrinos",
	"Dewpider": "Araqua",
	"Araquanid": "Tarenbulle",
	"Araquanid-Totem": "Tarenbulle-Dominant",
	"Fomantis": "Mimantis",
	"Lurantis": "Floramantis",
	"Lurantis-Totem": "Floramantis-Dominant",
	"Morelull": "Spododo",
	"Shiinotic": "Lampignon",
	"Salandit": "Tritox",
	"Salazzle": "Malamandre",
	"Salazzle-Totem": "Malamandre-Dominant",
	"Stufful": "Nounourson",
	"Bewear": "Chelours",
	"Bounsweet": "Croquine",
	"Steenee": "Candine",
	"Tsareena": "Sucreine",
	"Comfey": "Guérilande",
	"Oranguru": "Gouroutan",
	"Passimian": "Quartermac",
	"Wimpod": "Sovkipou",
	"Golisopod": "Sarmuraï",
	"Sandygast": "Bacabouh",
	"Palossand": "Trépassable",
	"Pyukumuku": "Concombaffe",
	"Type: Null": "Type:0",
	"Silvally": "Silvallié",
	"Silvally-Bug": "Silvallié-Insecte",
	"Silvally-Dark": "Silvallié-Ténèbres",
	"Silvally-Dragon": "Silvallié-Dragon",
	"Silvally-Electric": "Silvallié-Électrik",
	"Silvally-Fairy": "Silvallié-Fée",
	"Silvally-Fighting": "Silvallié-Combat",
	"Silvally-Fire": "Silvallié-Feu",
	"Silvally-Flying": "Silvallié-Vol",
	"Silvally-Ghost": "Silvallié-Spectre",
	"Silvally-Grass": "Silvallié-Plante",
	"Silvally-Ground": "Silvallié-Sol",
	"Silvally-Ice": "Silvallié-Glace",
	"Silvally-Poison": "Silvallié-Poison",
	"Silvally-Psychic": "Silvallié-Psy",
	"Silvally-Rock": "Silvallié-Roche",
	"Silvally-Steel": "Silvallié-Acier",
	"Silvally-Water": "Silvallié-Eau",
	"Minior": "Météno",
	"Minior-Meteor": "Météno-Météore",
	"Minior-Orange": "Météno-Orange",
	"Minior-Yellow": "Météno-Jaune",
	"Minior-Green": "Météno-Vert",
	"Minior-Blue": "Météno-Bleu",
	"Minior-Indigo": "Météno-Indigo",
	"Minior-Violet": "Météno-Violet",
	"Komala": "Dodoala",
	"Turtonator": "Boumata",
	"Togedemaru": "Togedemaru",
	"Togedemaru-Totem": "Togedemaru-Dominant",
	"Mimikyu": "Mimiqui",
	"Mimikyu-Busted": "Mimiqui-Démasqué",
	"Mimikyu-Totem": "Mimiqui-Dominant",
	"Mimikyu-Busted-Totem": "Mimiqui-Dominant-Démasqué",
	"Bruxish": "Denticrisse",
	"Drampa": "Draïeul",
	"Dhelmise": "Sinistrail",
	"Jangmo-o": "Bébécaille",
	"Hakamo-o": "Écaïd",
	"Kommo-o": "Ékaïser",
	"Kommo-o-Totem": "Ékaïser-Dominant",
	"Tapu Koko": "Tokorico",
	"Tapu Lele": "Tokopiyon",
	"Tapu Bulu": "Tokotoro",
	"Tapu Fini": "Tokopisco",
	"Cosmog": "Cosmog",
	"Cosmoem": "Cosmovum",
	"Solgaleo": "Solgaleo",
	"Lunala": "Lunala",
	"Nihilego": "Zéroïd",
	"Buzzwole": "Mouscoto",
	"Pheromosa": "Cancrelove",
	"Xurkitree": "Câblifère",
	"Celesteela": "Bamboiselle",
	"Kartana": "Katagami",
	"Guzzlord": "Engloutyran",
	"Necrozma": "Necrozma",
	"Necrozma-Dawn-Wings": "Necrozma-Aurore",
	"Necrozma-Dusk-Mane": "Necrozma-Couchant",
	"Necrozma-Ultra": "Necrozma-Ultra",
	"Magearna": "Magearna",
	"Magearna-Original": "Magearna-Passé",
	"Marshadow": "Marshadow",
	"Poipole": "Vémini",
	"Naganadel": "Mandrillon",
	"Stakataka": "Ama-Ama",
	"Blacephalon": "Pierroteknik",
	"Zeraora": "Zeraora",
	"Meltan": "Meltan",
	"Melmetal": "Melmetal",
	"Melmetal-Gmax": "Melmetal-Gmax",
	"Grookey": "Ouistempo",
	"Thwackey": "Badabouin",
	"Rillaboom": "Gorythmic",
	"Rillaboom-Gmax": "Gorythmic-Gmax",
	"Scorbunny": "Flambino",
	"Raboot": "Lapyro",
	"Cinderace": "Pyrobut",
	"Cinderace-Gmax": "Pyrobut-Gmax",
	"Sobble": "Larméléon",
	"Drizzile": "Arrozard",
	"Inteleon": "Lézargus",
	"Inteleon-Gmax": "Lézargus-Gmax",
	"Skwovet": "Rongourmand",
	"Greedent": "Rongrigou",
	"Rookidee": "Minisange",
	"Corvisquire": "Bleuseille",
	"Corviknight": "Corvaillus",
	"Corviknight-Gmax": "Corvaillus-Gmax",
	"Blipbug": "Larvadar",
	"Dottler": "Coléodôme",
	"Orbeetle": "Astronelle",
	"Orbeetle-Gmax": "Astronelle-Gmax",
	"Nickit": "Goupilou",
	"Thievul": "Roublenard",
	"Gossifleur": "Tournicoton",
	"Eldegoss": "Blancoton",
	"Wooloo": "Moumouton",
	"Dubwool": "Moumouflon",
	"Chewtle": "Khélocrok",
	"Drednaw": "Torgamord",
	"Drednaw-Gmax": "Torgamord-Gmax",
	"Yamper": "Voltoutou",
	"Boltund": "Fulgudog",
	"Rolycoly": "Charbi",
	"Carkol": "Wagomine",
	"Coalossal": "Monthracite",
	"Coalossal-Gmax": "Monthracite-Gmax",
	"Applin": "Verpom",
	"Flapple": "Pomdrapi",
	"Flapple-Gmax": "Pomdrapi-Gmax",
	"Appletun": "Dratatin",
	"Appletun-Gmax": "Dratatin-Gmax",
	"Silicobra": "Dunaja",
	"Sandaconda": "Dunaconda",
	"Sandaconda-Gmax": "Dunaconda-Gmax",
	"Cramorant": "Nigosier",
	"Cramorant-Gorging": "Nigosier-Gobe-Chu",
	"Cramorant-Gulping": "Nigosier-Gobe-Tout",
	"Arrokuda": "Embrochet",
	"Barraskewda": "Hastacuda",
	"Toxel": "Toxizap",
	"Toxtricity": "Salarsen",
	"Toxtricity-Low-Key": "Salarsen-Grave",
	"Toxtricity-Gmax": "Salarsen-Gmax",
	"Toxtricity-Low-Key-Gmax": "Salarsen-Grave-Gmax",
	"Sizzlipede": "Grillepattes",
	"Centiskorch": "Scolocendre",
	"Centiskorch-Gmax": "Scolocendre-Gmax",
	"Clobbopus": "Poulpaf",
	"Grapploct": "Krakos",
	"Sinistea": "Théffroi",
	"Sinistea-Antique": "Théffroi-Antique",
	"Polteageist": "Polthégeist",
	"Polteageist-Antique": "Polthégeist-Antique",
	"Hatenna": "Bibichut",
	"Hattrem": "Chapotus",
	"Hattrem-Gmax": "Chapotus-Gmax",
	"Hatterene": "Sorcilence",
	"Impidimp": "Grimalin",
	"Morgrem": "Fourbelin",
	"Grimmsnarl": "Angoliath",
	"Grimmsnarl-Gmax": "Angoliath-Gmax",
	"Obstagoon": "Ixon",
	"Perrserker": "Berserkatt",
	"Cursola": "Corayôme",
	"Sirfetch’d": "Palarticho",
	"Mr. Rime": "M. Glaquette",
	"Runerigus": "Tutétékri",
	"Milcery": "Crèmy",
	"Alcremie": "Charmilly",
	"Alcremie-Ruby-Cream": "Charmilly-Lait Ruby",
	"Alcremie-Matcha-Cream": "Charmilly-Lait Matcha",
	"Alcremie-Mint-Cream": "Charmilly-Lait Menthe",
	"Alcremie-Lemon-Cream": "Charmilly-Lait Citron",
	"Alcremie-Salted-Cream": "Charmilly-Lait Salé",
	"Alcremie-Ruby-Swirl": "Charmilly-Mélange-Ruby",
	"Alcremie-Caramel-Swirl": "Charmilly-Mélange-Caramel",
	"Alcremie-Rainbow-Swirl": "Charmilly-Mélange-Tricolore",
	"Alcremie-Gmax": "Charmilly-Gmax",
	"Falinks": "Hexadron",
	"Pincurchin": "Wattapik",
	"Snom": "Frissonille",
	"Frosmoth": "Beldeneige",
	"Stonjourner": "Dolman",
	"Eiscue": "Bekaglaçon",
	"Eiscue-Noice": "Bekaglaçon-Tête Dégel",
	"Indeedee": "Wimessir",
	"Indeedee-F": "Wimessir-F",
	"Morpeko": "Morpeko",
	"Morpeko-Hangry": "Morpeko-Affamé",
	"Cufant": "Charibari",
	"Copperajah": "Pachyradjah",
	"Copperajah-Gmax": "Pachyradjah-Gmax",
	"Dracozolt": "Galvagon",
	"Arctozolt": "Galvagla",
	"Dracovish": "Hydragon",
	"Arctovish": "Hydragla",
	"Duraludon": "Duralugon",
	"Duraludon-Gmax": "Duralugon-Gmax",
	"Dreepy": "Fantyrm",
	"Drakloak": "Dispareptil",
	"Dragapult": "Lanssorien",
	"Zacian": "Zacian",
	"Zacian-Crowned": "Zacian-Épée",
	"Zamazenta": "Zamazenta",
	"Zamazenta-Crowned": "Zamazenta-Bouclier",
	"Eternatus": "Éthernatos",
	"Eternatus-Eternamax": "Éthernatos-Infinimax",
	"Kubfu": "Wushours",
	"Urshifu": "Shifours",
	"Urshifu-Rapid-Strike": "Shifours-Mille Poings",
	"Urshifu-Gmax": "Shifours-Gmax",
	"Urshifu-Rapid-Strike-Gmax": "Shifours-Mille Poings-Gmax",
	"Zarude": "Zarude",
	"Zarude-Dada": "Zarude-Papa",
	"Regieleki": "Regieleki",
	"Regidrago": "Regidrago",
	"Glastrier": "Blizzeval",
	"Spectrier": "Spectreval",
	"Calyrex": "Sylveroy",
	"Calyrex-Ice": "Sylveroy-Froid",
	"Calyrex-Shadow": "Sylveroy-Effroi",
	"Wyrdeer": "Cerbyllin",
	"Kleavor": "Hachécateur",
	"Ursaluna": "Ursaking",
	"Basculegion": "Paragruel",
	"Basculegion-F": "Paragruel-F",
	"Sneasler": "Farfurex",
	"Overqwil": "Qwilpik",
	"Enamorus": "Amovénus",
	"Enamorus-Therian": "Amovénus-Totem"
};

export const CosmeticFormsDico: Array<string> = [
	"Unown-B",
	"Unown-C",
	"Unown-D",
	"Unown-E",
	"Unown-F",
	"Unown-G",
	"Unown-H",
	"Unown-I",
	"Unown-J",
	"Unown-K",
	"Unown-L",
	"Unown-M",
	"Unown-N",
	"Unown-O",
	"Unown-P",
	"Unown-Q",
	"Unown-R",
	"Unown-S",
	"Unown-T",
	"Unown-U",
	"Unown-V",
	"Unown-W",
	"Unown-X",
	"Unown-Y",
	"Unown-Z",
	"Unown-Exclamation",
	"Unown-Question",
	"Burmy-Sandy",
	"Burmy-Trash",
	"Shellos-East",
	"Gastrodon-East",
	"Deerling-Autumn",
	"Deerling-Summer",
	"Deerling-Winter",
	"Sawsbuck-Autumn",
	"Sawsbuck-Summer",
	"Sawsbuck-Winter",
	"Vivillon-Archipelago",
	"Vivillon-Continental",
	"Vivillon-Elegant",
	"Vivillon-Garden",
	"Vivillon-High Plains",
	"Vivillon-Icy Snow",
	"Vivillon-Jungle",
	"Vivillon-Marine",
	"Vivillon-Modern",
	"Vivillon-Monsoon",
	"Vivillon-Ocean",
	"Vivillon-Polar",
	"Vivillon-River",
	"Vivillon-Sandstorm",
	"Vivillon-Savanna",
	"Vivillon-Sun",
	"Vivillon-Tundra",
	"Flabe\u0301be\u0301-Blue",
	"Flabe\u0301be\u0301-Orange",
	"Flabe\u0301be\u0301-White",
	"Flabe\u0301be\u0301-Yellow",
	"Floette-Blue",
	"Floette-Orange",
	"Floette-White",
	"Floette-Yellow",
	"Florges-Blue",
	"Florges-Orange",
	"Florges-White",
	"Florges-Yellow",
	"Furfrou-Dandy",
	"Furfrou-Debutante",
	"Furfrou-Heart",
	"Furfrou-Diamond",
	"Furfrou-Kabuki",
	"Furfrou-La Reine",
	"Furfrou-Matron",
	"Furfrou-Pharaoh",
	"Furfrou-Star",
	"Minior-Orange",
	"Minior-Yellow",
	"Minior-Green",
	"Minior-Blue",
	"Minior-Indigo",
	"Minior-Violet",
	"Alcremie-Ruby-Cream",
	"Alcremie-Matcha-Cream",
	"Alcremie-Mint-Cream",
	"Alcremie-Lemon-Cream",
	"Alcremie-Salted-Cream",
	"Alcremie-Ruby-Swirl",
	"Alcremie-Caramel-Swirl",
	"Alcremie-Rainbow-Swirl"
]

export const AbilitiesDico: { [englishName: string]: string; } = {
	"No Ability": "Pas de Talent",
    "Stench": "Puanteur",
    "Drizzle": "Crachin",
    "Speed Boost": "Turbo",
    "Battle Armor": "Armurbaston",
    "Sturdy": "Fermeté",
    "Damp": "Moiteur",
    "Limber": "Échauffement",
    "Sand Veil": "Voile Sable",
    "Static": "Statik",
    "Volt Absorb": "Absorb Volt",
    "Water Absorb": "Absorb Eau",
    "Oblivious": "Benêt",
    "Cloud Nine": "Ciel Gris",
    "Compound Eyes": "Œil Composé",
    "Insomnia": "Insomnia",
    "Color Change": "Déguisement",
    "Immunity": "Vaccin",
    "Flash Fire": "Torche",
    "Shield Dust": "Écran Poudre",
    "Own Tempo": "Tempo Perso",
    "Suction Cups": "Ventouse",
    "Intimidate": "Intimidation",
    "Shadow Tag": "Marque Ombre",
    "Rough Skin": "Peau Dure",
    "Wonder Guard": "Garde Mystik",
    "Levitate": "Lévitation",
    "Effect Spore": "Pose Spore",
    "Synchronize": "Synchro",
    "Clear Body": "Corps Sain",
    "Natural Cure": "Médic Nature",
    "Lightning Rod": "Paratonnerre",
    "Serene Grace": "Sérénité",
    "Swift Swim": "Glissade",
    "Chlorophyll": "Chlorophyle",
    "Illuminate": "Lumiattirance",
    "Trace": "Calque",
    "Huge Power": "Coloforce",
    "Poison Point": "Point Poison",
    "Inner Focus": "Attention",
    "Magma Armor": "Armumagma",
    "Water Veil": "Ignifu-Voile",
    "Magnet Pull": "Magnépiège",
    "Soundproof": "Anti-Bruit",
    "Rain Dish": "Cuvette",
    "Sand Stream": "Sable Volant",
    "Pressure": "Pression",
    "Thick Fat": "Isograisse",
    "Early Bird": "Matinal",
    "Flame Body": "Corps Ardent",
    "Run Away": "Fuite",
    "Keen Eye": "Regard Vif",
    "Hyper Cutter": "Hyper Cutter",
    "Pickup": "Ramassage",
    "Truant": "Absentéisme",
    "Hustle": "Agitation",
    "Cute Charm": "Joli Sourire",
    "Plus": "Plus",
    "Minus": "Minus",
    "Forecast": "Météo",
    "Sticky Hold": "Glue",
    "Shed Skin": "Mue",
    "Guts": "Cran",
    "Marvel Scale": "Écaille Spéciale",
    "Liquid Ooze": "Suintement",
    "Overgrow": "Engrais",
    "Blaze": "Brasier",
    "Torrent": "Torrent",
    "Swarm": "Essaim",
    "Rock Head": "Tête de Roc",
    "Drought": "Sécheresse",
    "Arena Trap": "Piège Sable",
    "Vital Spirit": "Esprit Vital",
    "White Smoke": "Écran Fumée",
    "Pure Power": "Force Pure",
    "Shell Armor": "Coque Armure",
    "Air Lock": "Air Lock",
    "Tangled Feet": "Pieds Confus",
    "Motor Drive": "Motorisé",
    "Rivalry": "Rivalité",
    "Steadfast": "Impassible",
    "Snow Cloak": "Rideau Neige",
    "Gluttony": "Gloutonnerie",
    "Anger Point": "Colérique",
    "Unburden": "Délestage",
    "Heatproof": "Ignifugé",
    "Simple": "Simple",
    "Dry Skin": "Peau Sèche",
    "Download": "Télécharge",
    "Iron Fist": "Poing de Fer",
    "Poison Heal": "Soin Poison",
    "Adaptability": "Adaptabilité",
    "Skill Link": "Multi-Coups",
    "Hydration": "Hydratation",
    "Solar Power": "Force Soleil",
    "Quick Feet": "Pied Véloce",
    "Normalize": "Normalise",
    "Sniper": "Sniper",
    "Magic Guard": "Garde Magik",
    "No Guard": "Annule Garde",
    "Stall": "Frein",
    "Technician": "Technicien",
    "Leaf Guard": "Feuille Garde",
    "Klutz": "Maladresse",
    "Mold Breaker": "Brise Moule",
    "Super Luck": "Chanceux",
    "Aftermath": "Boom Final",
    "Anticipation": "Anticipation",
    "Forewarn": "Prédiction",
    "Unaware": "Inconscient",
    "Tinted Lens": "Lentiteintée",
    "Filter": "Filtre",
    "Slow Start": "Début Calme",
    "Scrappy": "Querelleur",
    "Storm Drain": "Lavabo",
    "Ice Body": "Corps Gel",
    "Solid Rock": "Solide Roc",
    "Snow Warning": "Alerte Neige",
    "Honey Gather": "Cherche Miel",
    "Frisk": "Fouille",
    "Reckless": "Téméraire",
    "Multitype": "Multi-Type",
    "Flower Gift": "Don Floral",
    "Bad Dreams": "Mauvais Rêve",
    "Pickpocket": "Pickpocket",
    "Sheer Force": "Sans Limite",
    "Contrary": "Contestation",
    "Unnerve": "Tension",
    "Defiant": "Acharné",
    "Defeatist": "Défaitiste",
    "Cursed Body": "Corps Maudit",
    "Healer": "Cœur Soin",
    "Friend Guard": "Garde Amie",
    "Weak Armor": "Armurouillée",
    "Heavy Metal": "Heavy Metal",
    "Light Metal": "Light Metal",
    "Multiscale": "Multiécaille",
    "Toxic Boost": "Rage Poison",
    "Flare Boost": "Rage Brûlure",
    "Harvest": "Récolte",
    "Telepathy": "Télépathe",
    "Moody": "Lunatique",
    "Overcoat": "Envelocape",
    "Poison Touch": "Toxitouche",
    "Regenerator": "Régé-Force",
    "Big Pecks": "Cœur de Coq",
    "Sand Rush": "Baigne Sable",
    "Wonder Skin": "Peau Miracle",
    "Analytic": "Analyste",
    "Illusion": "Illusion",
    "Imposter": "Imposteur",
    "Infiltrator": "Infiltration",
    "Mummy": "Momie",
    "Moxie": "Impudence",
    "Justified": "Cœur Noble",
    "Rattled": "Phobique",
    "Magic Bounce": "Miroir Magik",
    "Sap Sipper": "Herbivore",
    "Prankster": "Farceur",
    "Sand Force": "Force Sable",
    "Iron Barbs": "Épine de Fer",
    "Zen Mode": "Mode Transe",
    "Victory Star": "Victorieux",
    "Turboblaze": "TurboBrasier",
    "Teravolt": "Téra-Voltage",
    "Aroma Veil": "Aroma-Voile",
    "Flower Veil": "Flora-Voile",
    "Cheek Pouch": "Bajoues",
    "Protean": "Protéen",
    "Fur Coat": "Toison Épaisse",
    "Magician": "Magicien",
    "Bulletproof": "Pare-Balles",
    "Competitive": "Battant",
    "Strong Jaw": "Prognathe",
    "Refrigerate": "Peau Gelée",
    "Sweet Veil": "Gluco-Voile",
    "Stance Change": "Déclic Tactique",
    "Gale Wings": "Ailes Bourrasque",
    "Mega Launcher": "Méga Blaster",
    "Grass Pelt": "Toison Herbue",
    "Symbiosis": "Symbiose",
    "Tough Claws": "Griffe Dure",
    "Pixilate": "Peau Féérique",
    "Gooey": "Poisseux",
    "Parental Bond": "Amour Filial",
    "Aerilate": "Peau Céleste",
    "Dark Aura": "Aura Ténébreuse",
    "Fairy Aura": "Aura Féérique",
    "Aura Break": "Aura Inversée",
    "As One (Glastrier)": "Osmose Équine (Blizzeval)",
    "As One (Spectrier)": "Osmose Équine (Spectreval)",
    "Libero": "Libéro",
    "Gorilla Tactics": "Entêtement",
    "Desolate Land": "Terre Finale",
    "Primordial Sea": "Mer Primaire",
    "Shadow Shield": "Spectro-Bouclier",
    "Soul-Heart": "Animacœur",
    "Beast Boost": "Boost Chimère",
    "Prism Armor": "Prisme-Armure",
    "Neuroforce": "Cérébro-Force",
    "Delta Stream": "Souffle Delta",
    "Full Metal Body": "Métallo-Garde",
    "Grim Neigh": "Sombre Ruade",
    "Chilling Neigh": "Blanche Ruade",
    "Unseen Fist": "Poing Invisible",
    "Intrepid Sword": "Lame Indomptable",
    "Dauntless Shield": "Égide Inflexible",
    "Power Construct": "Rassemblement",
    "(Power Construct)": "(Rassemblement)",
    "Mirror Armor": "Armure Miroir",
    "Battle Bond": "Synergie",
    "(Battle Bond)": "(Synergie)",
    "Grassy Surge": "Créa-Herbe",
    "Misty Surge": "Créa-Brume",
    "Electric Surge": "Créa-Élec",
    "Psychic Surge": "Créa-Psy",
    "Berserk": "Dracolère",
    "Transistor": "Transistor",
    "Liquid Voice": "Hydrata-Son",
    "Water Bubble": "Aquabulle",
    "Slush Rush": "Chasse-Neige",
    "Propeller Tail": "Propulseur",
    "Gulp Missile": "Dégobage",
    "Perish Body": "Corps Condamné",
    "Long Reach": "Longue Portée",
    "Steelworker": "Expert Acier",
    "Stalwart": "Nerfs d’Acier",
    "Ice Face": "Tête de Gel",
    "Ice Scales": "Écailles Glacées",
    "Galvanize": "Peau Électrique",
    "Emergency Exit": "Repli Tactique",
    "Comatose": "Hypersommeil",
    "Disguise": "Fantômasque",
    "Shields Down": "Bouclier-Carcan",
    "Hunger Switch": "Déclic Fringale",
    "Power of Alchemy": "Osmose",
    "Dancer": "Danseuse",
    "Water Compaction": "Sable Humide",
    "Receiver": "Receveur",
    "Steely Spirit": "Boost Acier",
    "Innards Out": "Expuls'Organes",
    "Surge Surfer": "Surf Caudal",
    "Dragon's Maw": "Dent de Dragon",
    "Wandering Spirit": "Âme Vagabonde",
    "Corrosion": "Corrosion",
    "RKS System": "Système Alpha",
    "Power Spot": "Cercle d’Énergie",
    "Mimicry": "Mimétisme",
    "Stakeout": "Filature",
    "Schooling": "Banc",
    "Battery": "Batterie",
    "Wimp Out": "Escampette",
    "Ball Fetch": "Ramasse Ball",
    "Merciless": "Cruauté",
    "Curious Medicine": "Breuvage Suspect",
    "Quick Draw": "Tir Vif",
    "Ripen": "Mûrissement",
    "Fluffy": "Boule de Poils",
    "Dazzling": "Corps Coloré",
    "Steam Engine": "Turbine",
    "Triage": "Prioguérison",
    "Tangling Hair": "Mèche Rebelle",
    "Cotton Down": "Effilochage",
    "Screen Cleaner": "Brise-Barrière",
    "Stamina": "Endurance",
    "Pastel Veil": "Voile Pastel",
    "Sand Spit": "Expul’Sable",
    "Punk Rock": "Punk Rock",
    "Queenly Majesty": "Prestance Royale",
    "Neutralizing Gas": "Gaz Inhibiteur"
}

export const TypesDico: { [englishName: string]: string; } = {
    "Bug": "Insecte",
	"Dark": "Ténèbres",
	"Dragon": "Dragon",
	"Electric": "Électrik",
	"Fairy": "Fée",
	"Fighting": "Combat",
	"Fire": "Feu",
	"Flying": "Vol",
	"Ghost": "Spectre",
	"Grass": "Plante",
	"Ground": "Sol",
	"Ice": "Glace",
    "Normal": "Normal",
	"Poison": "Poison",
	"Psychic": "Psy",
	"Rock": "Roche",
	"Steel": "Acier",
	"Water": "Eau"
}

export const HeadersDico: { [englishName: string]: string; } = {
    "Abilities": "Talents",
    "Hidden Ability": "Talent caché",
    "Special Event Ability": "Talent événementiel",
    "Situational Abilities": "Talents situationnels",
    "Unviable Abilities": "Talents non viables",
	"Moves": "Capacités",
    "Physical moves": "Capacités physiques",
    "Special moves": "Capacités spéciales",
    "Status moves": "Capacités de statut",
    "Usually useless moves": "Capacités généralement inutiles",
    "Sketched moves": "Capacités gribouillées",
    "Useless sketched moves": "Capacités gribouillées inutiles",
	"Items": "Objets",
    "Popular items": "Objets populaires",
    "Pokémon-specific items": "Objets spécifiques à un Pokémon",
    "Usually useless items": "Objets généralement inutiles",
    "Useless items": "Objets inutiles",
    "Restricted Legendary": "Légendaires restreints",
    "Regular": "Standard",
    "Mythical": "Fabuleux",
    "New": "Nouveau",
    "Below PU": "Sous le PU",
    "Below DUU": "Sous le DUU",
    "NFEs not in a higher tier": "NFEs non présents dans un tier supérieur",
    "Illegal results": "Résultats illégaux",
    "CAP moves": "Capacités CAP",
}

export const MenuDico: { [englishName: string]: string; } = {
    "Copy": "Copier",
    "Import/Export": "Importer/Exporter",
    "Move": "Déplacer",
    "Delete": "Supprimer",
}

export const FiltersDico:  { [englishName: string]: string; } = {
    "HP": "PV",
    "Atk": "Atq",
    "Def": "Def",
    "SpA": "SpA",
	"SpD": "SpD",
	"Spe": "Vit",
	"BST": "BST",
	"Sort: ": "Tri :",
	"Name": "Nom",
	"Types" : "Types",
	"Abilities": "Talents",
	"Number" : "Numéro"
}